import { notification } from 'antd';

import {
  getFlowList,
  getFlowInfo,
  preSet,
  getStartList,
  stepStart,
  doWithdraw,
  startDetail,
  getFlowChart,
} from '../services/start';
import defaultReducers from '../reducers';

export default {
  namespace: 'start',
  state: {
    startDetails: {},
    availableFlows: [],
    flowChart: [],
    processingStart: {},
    preStepData: {
      available_steps: [
        {
          id: 408,
          name: '第二步',
          approver_type: 0,
          approvers: [],
        },
        {
          id: 409,
          name: 'test',
          approver_type: 0,
          approvers: [],
        },
      ],
      step_end: 0,
      timestamp: 1546483127,
      concurrent_type: 1,
      flow_id: 93,
      step_run_id: null,
      message: '',
      is_cc: '1',
      cc_person: [
        {
          staff_name: '刘勇01',
          staff_sn: 110103,
        },
      ],
    },
    flowDetails: {
      '6': {
        step: {
          id: 415,
          name: '发起',
          description: '',
          flow_id: 96,
          step_key: 1,
          prev_step_key: [],
          next_step_key: [2, 3],
          available_fields: [
            'grid.*.dep',
            'grid.*.deps',
            'grid.*.staff',
            'grid.*.staffs',
            'grid.*.shop',
            'grid.*.shops',
            'shops',
            'shop',
            'depar',
            'depart',
            'staff',
            'staffs',
            'number',
            'grid.*.time',
            'single',
            'multi',
            'arra',
            'file',
            'area',
            'interface',
            'interfaces',
            'date',
            'text',
            'grid',
            'grid.*.interface',
            'grid.*.interfaces',
            'grid.*.files',
          ],
          hidden_fields: [],
          editable_fields: [
            'file',
            'number',
            'area',
            'single',
            'multi',
            'arra',
            'depart',
            'depar',
            'staff',
            'staffs',
            'shop',
            'shops',
            'interface',
            'interfaces',
            'date',
            'text',
            'grid',
            'grid.*.dep',
            'grid.*.deps',
            'grid.*.staff',
            'grid.*.staffs',
            'grid.*.shop',
            'grid.*.shops',
            'grid.*.interface',
            'grid.*.interfaces',
            'grid.*.files',
            'grid.*.time',
          ],
          required_fields: [],
          allow_condition: '',
          skip_condition: '',
          reject_type: 1,
          concurrent_type: 1,
          merge_type: 0,
        },
        form_data: {
          file: [],
          number: 1.1,
          area: [],
          single: '给',
          multi: ['发', '额'],
          arra: ['2', '5'],
          depart: {
            value: '2',
            text: '总经办',
          },
          depar: [],
          staff: {
            text: '陈贤喜',
            value: 100001,
          },
          staffs: [
            {
              text: '陈贤喜',
              value: 100001,
            },
            {
              text: '罗刚',
              value: 110001,
            },
            {
              text: '代涛',
              value: 110002,
            },
            {
              text: '谢欢',
              value: 110003,
            },
            {
              text: '岳海生',
              value: 110004,
            },
            {
              text: '肖龙伟',
              value: 110005,
            },
            {
              text: '胡长蜜',
              value: 110006,
            },
            {
              text: '夏克华',
              value: 110007,
            },
            {
              text: '贾桃',
              value: 110009,
            },
            {
              text: '郭中华',
              value: 110013,
            },
          ],
          shop: {
            value: 'lsc1374',
            text: '陕西C02.延安市宜川县JB-47C',
          },
          shops: [
            {
              value: 'lsw2729',
              text: '河南C02.南阳市ODVS-400A1+C',
            },
          ],
          interface: '7',
          interfaces: ['292'],
          date: '2018-11-01',
          text: '4554',
          grid: [],
        },
        fields: {
          form: [
            {
              id: '759',
              key: 'file',
              name: '文件',
              description: '',
              type: 'file',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '',
              max: '',
              scale: 0,
              default_value: '',
              options: [],
              form_id: 41,
              form_grid_id: null,
              sort: 0,
              field_api_configuration_id: null,
              row: 2,
              col: 8,
              x: 0,
              y: 0,
              mobile_y: null,
              validator_id: [7],
              available_options: [],
              validator: [
                {
                  id: 7,
                  name: '文件',
                  description: '',
                  type: 'mimes',
                  params:
                    'jpeg,png,gif,psd,swf,bmp,emf,txt,html,htm,pdf,xlsx,xls,doc,docx,ppt,zip,rar,log,sql,mp4,3gp,avi,mp3,wmv,wave',
                  is_locked: 0,
                  created_at: '2018-12-04 09:28:19',
                  updated_at: '2018-12-04 09:28:19',
                  pivot: {
                    field_id: 759,
                    validator_id: 7,
                  },
                },
              ],
              widgets: [],
            },
            {
              id: 760,
              key: 'number',
              name: '数字',
              description: '',
              type: 'int',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '-100',
              max: '',
              scale: 1,
              default_value: '1.1',
              options: [],
              form_id: 41,
              form_grid_id: null,
              sort: 1,
              field_api_configuration_id: null,
              row: 1,
              col: 4,
              x: 0,
              y: 2,
              mobile_y: null,
              validator_id: [],
              available_options: [],
              validator: [],
              widgets: [],
            },
            {
              id: 761,
              key: 'area',
              name: '地点',
              description: '',
              type: 'region',
              is_checkbox: 0,
              condition: null,
              region_level: 4,
              min: '',
              max: '',
              scale: 0,
              default_value: [],
              options: [],
              form_id: 41,
              form_grid_id: null,
              sort: 2,
              field_api_configuration_id: null,
              row: 2,
              col: 8,
              x: 0,
              y: 4,
              mobile_y: null,
              validator_id: [],
              available_options: [],
              validator: [],
              widgets: [],
            },
            {
              id: 762,
              key: 'single',
              name: '单选',
              description: '',
              type: 'select',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '',
              max: '',
              scale: 0,
              default_value: '给',
              options: ['给', '我', '发'],
              form_id: 41,
              form_grid_id: null,
              sort: 3,
              field_api_configuration_id: null,
              row: 1,
              col: 5,
              x: 4,
              y: 2,
              mobile_y: null,
              validator_id: [],
              available_options: [],
              validator: [],
              widgets: [],
            },
            {
              id: 763,
              key: 'multi',
              name: '多选',
              description: '',
              type: 'select',
              is_checkbox: 1,
              condition: null,
              region_level: null,
              min: '2',
              max: '3',
              scale: 0,
              default_value: ['发', '额'],
              options: ['发', '额', '过', 'p', 'h'],
              form_id: 41,
              form_grid_id: null,
              sort: 4,
              field_api_configuration_id: null,
              row: 1,
              col: 9,
              x: 1,
              y: 3,
              mobile_y: null,
              validator_id: [],
              available_options: [],
              validator: [],
              widgets: [],
            },
            {
              id: 764,
              key: 'arra',
              name: '数组',
              description: '',
              type: 'array',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '2',
              max: '10',
              scale: 0,
              default_value: ['2', '5'],
              options: [],
              form_id: 41,
              form_grid_id: null,
              sort: 5,
              field_api_configuration_id: null,
              row: 1,
              col: 9,
              x: 1,
              y: 6,
              mobile_y: null,
              validator_id: [],
              available_options: [],
              validator: [],
              widgets: [],
            },
            {
              id: 765,
              key: 'depart',
              name: '部门单选',
              description: '',
              type: 'department',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '',
              max: '',
              scale: 0,
              default_value: {
                value: '2',
                text: '总经办',
              },
              options: [],
              form_id: 41,
              form_grid_id: null,
              sort: 6,
              field_api_configuration_id: null,
              row: 1,
              col: 4,
              x: 0,
              y: 7,
              mobile_y: null,
              validator_id: [],
              available_options: [
                {
                  value: '1',
                  text: '未分配',
                },
                {
                  value: '2',
                  text: '总经办',
                },
                {
                  value: '3',
                  text: '运营部',
                },
                {
                  value: '4',
                  text: '财务部',
                },
                {
                  value: '5',
                  text: '企划部',
                },
                {
                  value: '6',
                  text: '数据部',
                },
                {
                  value: '7',
                  text: 'IT部',
                },
                {
                  value: '163',
                  text: '数据部-长鲨',
                },
                {
                  value: '164',
                  text: '数据部-短鲨',
                },
                {
                  value: '165',
                  text: '数据部-GO',
                },
                {
                  value: '166',
                  text: '数据部-杰尼威尼',
                },
              ],
              validator: [],
              widgets: [
                {
                  id: 3313,
                  field_id: 765,
                  value: '1',
                  text: '未分配',
                },
                {
                  id: 3314,
                  field_id: 765,
                  value: '2',
                  text: '总经办',
                },
                {
                  id: 3315,
                  field_id: 765,
                  value: '3',
                  text: '运营部',
                },
                {
                  id: 3316,
                  field_id: 765,
                  value: '4',
                  text: '财务部',
                },
                {
                  id: 3317,
                  field_id: 765,
                  value: '5',
                  text: '企划部',
                },
                {
                  id: 3318,
                  field_id: 765,
                  value: '6',
                  text: '数据部',
                },
                {
                  id: 3319,
                  field_id: 765,
                  value: '7',
                  text: 'IT部',
                },
                {
                  id: 3320,
                  field_id: 765,
                  value: '163',
                  text: '数据部-长鲨',
                },
                {
                  id: 3321,
                  field_id: 765,
                  value: '164',
                  text: '数据部-短鲨',
                },
                {
                  id: 3322,
                  field_id: 765,
                  value: '165',
                  text: '数据部-GO',
                },
                {
                  id: 3323,
                  field_id: 765,
                  value: '166',
                  text: '数据部-杰尼威尼',
                },
              ],
            },
            {
              id: 766,
              key: 'depar',
              name: '部门多选',
              description: '',
              type: 'department',
              is_checkbox: 1,
              condition: null,
              region_level: null,
              min: '2',
              max: '4',
              scale: 0,
              default_value: [],
              options: [],
              form_id: 41,
              form_grid_id: null,
              sort: 7,
              field_api_configuration_id: null,
              row: 2,
              col: 8,
              x: 0,
              y: 7,
              mobile_y: null,
              validator_id: [],
              available_options: [
                {
                  value: '1',
                  text: '未分配',
                },
                {
                  value: '2',
                  text: '总经办',
                },
                {
                  value: '3',
                  text: '运营部',
                },
                {
                  value: '4',
                  text: '财务部',
                },
                {
                  value: '5',
                  text: '企划部',
                },
                {
                  value: '6',
                  text: '数据部',
                },
              ],
              validator: [],
              widgets: [
                {
                  id: 3324,
                  field_id: 766,
                  value: '1',
                  text: '未分配',
                },
                {
                  id: 3325,
                  field_id: 766,
                  value: '2',
                  text: '总经办',
                },
                {
                  id: 3326,
                  field_id: 766,
                  value: '3',
                  text: '运营部',
                },
                {
                  id: 3327,
                  field_id: 766,
                  value: '4',
                  text: '财务部',
                },
                {
                  id: 3328,
                  field_id: 766,
                  value: '5',
                  text: '企划部',
                },
                {
                  id: 3329,
                  field_id: 766,
                  value: '6',
                  text: '数据部',
                },
              ],
            },
            {
              id: 767,
              key: 'staff',
              name: '员工单选',
              description: '',
              type: 'staff',
              is_checkbox: 0,
              condition: '',
              region_level: null,
              min: '',
              max: '',
              scale: 0,
              default_value: {
                text: '陈贤喜',
                value: 100001,
              },
              options: [],
              form_id: 41,
              form_grid_id: null,
              sort: 8,
              field_api_configuration_id: null,
              row: 1,
              col: 4,
              x: 0,
              y: 9,
              mobile_y: null,
              validator_id: [],
              available_options: [],
              validator: [],
              widgets: [],
            },
            {
              id: 768,
              key: 'staffs',
              name: '员工多选',
              description: '',
              type: 'staff',
              is_checkbox: 1,
              condition: '',
              region_level: null,
              min: '1',
              max: '18',
              scale: 0,
              default_value: [
                {
                  text: '陈贤喜',
                  value: 100001,
                },
                {
                  text: '罗刚',
                  value: 110001,
                },
                {
                  text: '代涛',
                  value: 110002,
                },
                {
                  text: '谢欢',
                  value: 110003,
                },
                {
                  text: '岳海生',
                  value: 110004,
                },
                {
                  text: '肖龙伟',
                  value: 110005,
                },
                {
                  text: '胡长蜜',
                  value: 110006,
                },
                {
                  text: '夏克华',
                  value: 110007,
                },
                {
                  text: '贾桃',
                  value: 110009,
                },
                {
                  text: '郭中华',
                  value: 110013,
                },
              ],
              options: [],
              form_id: 41,
              form_grid_id: null,
              sort: 9,
              field_api_configuration_id: null,
              row: 2,
              col: 8,
              x: 0,
              y: 10,
              mobile_y: null,
              validator_id: [],
              available_options: [],
              validator: [],
              widgets: [],
            },
            {
              id: 769,
              key: 'shop',
              name: '店铺单选',
              description: '',
              type: 'shop',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '',
              max: '',
              scale: 0,
              default_value: {
                value: 'lsc1374',
                text: '陕西C02.延安市宜川县JB-47C',
              },
              options: [],
              form_id: 41,
              form_grid_id: null,
              sort: 10,
              field_api_configuration_id: null,
              row: 1,
              col: 4,
              x: 8,
              y: 11,
              mobile_y: null,
              validator_id: [],
              available_options: [],
              validator: [],
              widgets: [],
            },
            {
              id: 770,
              key: 'shops',
              name: '店铺多选',
              description: '',
              type: 'shop',
              is_checkbox: 1,
              condition: null,
              region_level: null,
              min: '',
              max: '',
              scale: 0,
              default_value: [
                {
                  value: 'lsw2729',
                  text: '河南C02.南阳市ODVS-400A1+C',
                },
              ],
              options: [],
              form_id: 41,
              form_grid_id: null,
              sort: 11,
              field_api_configuration_id: null,
              row: 2,
              col: 8,
              x: 0,
              y: 12,
              mobile_y: null,
              validator_id: [],
              available_options: [
                {
                  value: 'lsw2729',
                  text: '河南C02.南阳市ODVS-400A1+C',
                },
                {
                  value: 'lsc1203',
                  text: '四川B12.宜宾市14店KEDD-120A1',
                },
                {
                  value: 'lsc1374',
                  text: '陕西C02.延安市宜川县JB-47C',
                },
                {
                  value: 'lsw2755',
                  text: '江苏C02.苏州盛泽镇4店HLMP-350A2+C',
                },
                {
                  value: 'lsw2673',
                  text: '上海C02.川沙镇TLW-120B2',
                },
                {
                  value: 'lsc1406',
                  text: '四川C02.成都市青白江5店QPL-150A2',
                },
                {
                  value: 'lsw2683',
                  text: '浙江C02.余姚市BL-120B2',
                },
                {
                  value: 'lsc1332',
                  text: '云南C01.文山市4店BXN-260A2',
                },
                {
                  value: 'lsc951',
                  text: '重庆B09.开县9店SDY-200A2',
                },
                {
                  value: 'lsw2549',
                  text: '安徽B12.池州贵池区EGOU-180A2',
                },
              ],
              validator: [],
              widgets: [
                {
                  id: 3330,
                  field_id: 770,
                  value: 'lsw2729',
                  text: '河南C02.南阳市ODVS-400A1+C',
                },
                {
                  id: 3331,
                  field_id: 770,
                  value: 'lsc1203',
                  text: '四川B12.宜宾市14店KEDD-120A1',
                },
                {
                  id: 3332,
                  field_id: 770,
                  value: 'lsc1374',
                  text: '陕西C02.延安市宜川县JB-47C',
                },
                {
                  id: 3333,
                  field_id: 770,
                  value: 'lsw2755',
                  text: '江苏C02.苏州盛泽镇4店HLMP-350A2+C',
                },
                {
                  id: 3334,
                  field_id: 770,
                  value: 'lsw2673',
                  text: '上海C02.川沙镇TLW-120B2',
                },
                {
                  id: 3335,
                  field_id: 770,
                  value: 'lsc1406',
                  text: '四川C02.成都市青白江5店QPL-150A2',
                },
                {
                  id: 3336,
                  field_id: 770,
                  value: 'lsw2683',
                  text: '浙江C02.余姚市BL-120B2',
                },
                {
                  id: 3337,
                  field_id: 770,
                  value: 'lsc1332',
                  text: '云南C01.文山市4店BXN-260A2',
                },
                {
                  id: 3338,
                  field_id: 770,
                  value: 'lsc951',
                  text: '重庆B09.开县9店SDY-200A2',
                },
                {
                  id: 3339,
                  field_id: 770,
                  value: 'lsw2549',
                  text: '安徽B12.池州贵池区EGOU-180A2',
                },
              ],
            },
            {
              id: 771,
              key: 'interface',
              name: '接口（单选）',
              description: '',
              type: 'api',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '',
              max: '',
              scale: 0,
              default_value: '7',
              options: [],
              form_id: 41,
              form_grid_id: null,
              sort: 12,
              field_api_configuration_id: 1,
              row: 1,
              col: 4,
              x: 8,
              y: 12,
              mobile_y: null,
              validator_id: [],
              available_options: [],
              validator: [],
              widgets: [],
            },
            {
              id: 772,
              key: 'interfaces',
              name: '接口（多选）',
              description: '',
              type: 'api',
              is_checkbox: 1,
              condition: null,
              region_level: null,
              min: '',
              max: '',
              scale: 0,
              default_value: ['292'],
              options: [],
              form_id: 41,
              form_grid_id: null,
              sort: 13,
              field_api_configuration_id: 2,
              row: 2,
              col: 8,
              x: 4,
              y: 14,
              mobile_y: null,
              validator_id: [],
              available_options: [],
              validator: [],
              widgets: [],
            },
            {
              id: 773,
              key: 'date',
              name: '日期',
              description: '',
              type: 'date',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '',
              max: '',
              scale: 0,
              default_value: '2018-11-01',
              options: [],
              form_id: 41,
              form_grid_id: null,
              sort: 14,
              field_api_configuration_id: null,
              row: 1,
              col: 4,
              x: 0,
              y: 15,
              mobile_y: null,
              validator_id: [],
              available_options: [],
              validator: [],
              widgets: [],
            },
            {
              id: 774,
              key: 'text',
              name: '文本',
              description: '请输入..',
              type: 'text',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '1',
              max: '9',
              scale: 0,
              default_value: '4554',
              options: [],
              form_id: 41,
              form_grid_id: null,
              sort: 15,
              field_api_configuration_id: null,
              row: 1,
              col: 4,
              x: 0,
              y: 14,
              mobile_y: null,
              validator_id: [],
              available_options: [],
              validator: [],
              widgets: [],
            },
          ],
          grid: [
            {
              id: 41,
              name: '控件1',
              key: 'grid',
              row: 1,
              col: 12,
              x: 0,
              y: 16,
              form_id: 41,
              field_default_value: {
                dep: {
                  value: 1,
                  text: '未分配',
                },
                deps: [
                  {
                    value: 7,
                    text: 'IT部',
                  },
                ],
                staff: {
                  value: 110001,
                  text: '罗刚',
                },
                staffs: [
                  {
                    value: 110002,
                    text: '代涛',
                  },
                  {
                    value: 110001,
                    text: '罗刚',
                  },
                ],
                shop: {
                  value: 'lsw2729',
                  text: '河南C02.南阳市ODVS-400A1+C',
                },
                shops: '',
                interface: '4',
                interfaces: '',
                files: [],
                time: null,
              },
              fields: [
                {
                  id: 775,
                  key: 'dep',
                  name: '部门（单选）',
                  description: '',
                  type: 'department',
                  is_checkbox: 0,
                  condition: null,
                  region_level: null,
                  min: '',
                  max: '',
                  scale: 0,
                  default_value: {
                    value: 1,
                    text: '未分配',
                  },
                  options: [],
                  form_id: 41,
                  form_grid_id: 41,
                  sort: 0,
                  field_api_configuration_id: null,
                  row: 1,
                  col: 4,
                  x: 0,
                  y: 0,
                  mobile_y: null,
                  validator_id: [],
                  available_options: [
                    {
                      value: '1',
                      text: '未分配',
                    },
                    {
                      value: '2',
                      text: '总经办',
                    },
                    {
                      value: '3',
                      text: '运营部',
                    },
                    {
                      value: '4',
                      text: '财务部',
                    },
                    {
                      value: '5',
                      text: '企划部',
                    },
                    {
                      value: '6',
                      text: '数据部',
                    },
                  ],
                  validator: [],
                  widgets: [
                    {
                      id: 3340,
                      field_id: 775,
                      value: '1',
                      text: '未分配',
                    },
                    {
                      id: 3341,
                      field_id: 775,
                      value: '2',
                      text: '总经办',
                    },
                    {
                      id: 3342,
                      field_id: 775,
                      value: '3',
                      text: '运营部',
                    },
                    {
                      id: 3343,
                      field_id: 775,
                      value: '4',
                      text: '财务部',
                    },
                    {
                      id: 3344,
                      field_id: 775,
                      value: '5',
                      text: '企划部',
                    },
                    {
                      id: 3345,
                      field_id: 775,
                      value: '6',
                      text: '数据部',
                    },
                  ],
                },
                {
                  id: 776,
                  key: 'deps',
                  name: '部门（多选）',
                  description: '',
                  type: 'department',
                  is_checkbox: 1,
                  condition: null,
                  region_level: null,
                  min: '',
                  max: '',
                  scale: 0,
                  default_value: [
                    {
                      value: 7,
                      text: 'IT部',
                    },
                  ],
                  options: [],
                  form_id: 41,
                  form_grid_id: 41,
                  sort: 1,
                  field_api_configuration_id: null,
                  row: 2,
                  col: 8,
                  x: 4,
                  y: 0,
                  mobile_y: null,
                  validator_id: [],
                  available_options: [],
                  validator: [],
                  widgets: [],
                },
                {
                  id: 777,
                  key: 'staff',
                  name: '员工（单选）',
                  description: '',
                  type: 'staff',
                  is_checkbox: 0,
                  condition: '',
                  region_level: null,
                  min: '',
                  max: '',
                  scale: 0,
                  default_value: {
                    value: 110001,
                    text: '罗刚',
                  },
                  options: [],
                  form_id: 41,
                  form_grid_id: 41,
                  sort: 2,
                  field_api_configuration_id: null,
                  row: 1,
                  col: 4,
                  x: 0,
                  y: 1,
                  mobile_y: null,
                  validator_id: [],
                  available_options: [
                    {
                      value: '100001',
                      text: '陈贤喜',
                    },
                    {
                      value: '110001',
                      text: '罗刚',
                    },
                    {
                      value: '110002',
                      text: '代涛',
                    },
                    {
                      value: '110003',
                      text: '谢欢',
                    },
                    {
                      value: '110004',
                      text: '岳海生',
                    },
                    {
                      value: '110005',
                      text: '肖龙伟',
                    },
                    {
                      value: '110006',
                      text: '胡长蜜',
                    },
                    {
                      value: '110007',
                      text: '夏克华',
                    },
                    {
                      value: '110009',
                      text: '贾桃',
                    },
                    {
                      value: '110013',
                      text: '郭中华',
                    },
                  ],
                  validator: [],
                  widgets: [
                    {
                      id: 3346,
                      field_id: 777,
                      value: '100001',
                      text: '陈贤喜',
                    },
                    {
                      id: 3347,
                      field_id: 777,
                      value: '110001',
                      text: '罗刚',
                    },
                    {
                      id: 3348,
                      field_id: 777,
                      value: '110002',
                      text: '代涛',
                    },
                    {
                      id: 3349,
                      field_id: 777,
                      value: '110003',
                      text: '谢欢',
                    },
                    {
                      id: 3350,
                      field_id: 777,
                      value: '110004',
                      text: '岳海生',
                    },
                    {
                      id: 3351,
                      field_id: 777,
                      value: '110005',
                      text: '肖龙伟',
                    },
                    {
                      id: 3352,
                      field_id: 777,
                      value: '110006',
                      text: '胡长蜜',
                    },
                    {
                      id: 3353,
                      field_id: 777,
                      value: '110007',
                      text: '夏克华',
                    },
                    {
                      id: 3354,
                      field_id: 777,
                      value: '110009',
                      text: '贾桃',
                    },
                    {
                      id: 3355,
                      field_id: 777,
                      value: '110013',
                      text: '郭中华',
                    },
                  ],
                },
                {
                  id: 778,
                  key: 'staffs',
                  name: '员工（多选）',
                  description: '',
                  type: 'staff',
                  is_checkbox: 1,
                  condition: '',
                  region_level: null,
                  min: '',
                  max: '',
                  scale: 0,
                  default_value: [
                    {
                      value: 110002,
                      text: '代涛',
                    },
                    {
                      value: 110001,
                      text: '罗刚',
                    },
                  ],
                  options: [],
                  form_id: 41,
                  form_grid_id: 41,
                  sort: 3,
                  field_api_configuration_id: null,
                  row: 1,
                  col: 6,
                  x: 0,
                  y: 3,
                  mobile_y: null,
                  validator_id: [],
                  available_options: [
                    {
                      value: '100001',
                      text: '陈贤喜',
                    },
                    {
                      value: '110001',
                      text: '罗刚',
                    },
                    {
                      value: '110002',
                      text: '代涛',
                    },
                    {
                      value: '110003',
                      text: '谢欢',
                    },
                    {
                      value: '110004',
                      text: '岳海生',
                    },
                    {
                      value: '110005',
                      text: '肖龙伟',
                    },
                    {
                      value: '110006',
                      text: '胡长蜜',
                    },
                    {
                      value: '110007',
                      text: '夏克华',
                    },
                    {
                      value: '110009',
                      text: '贾桃',
                    },
                    {
                      value: '110013',
                      text: '郭中华',
                    },
                    {
                      value: '110014',
                      text: '周德微',
                    },
                    {
                      value: '110015',
                      text: '叶长久',
                    },
                    {
                      value: '110016',
                      text: '柴恭如',
                    },
                    {
                      value: '110017',
                      text: '杨德高',
                    },
                    {
                      value: '110019',
                      text: '罗双',
                    },
                    {
                      value: '110022',
                      text: '窦佳佳',
                    },
                    {
                      value: '110023',
                      text: '徐倚枫',
                    },
                    {
                      value: '110024',
                      text: '陈国平',
                    },
                    {
                      value: '110028',
                      text: '冯成刚',
                    },
                    {
                      value: '110033',
                      text: '唐洪秀',
                    },
                  ],
                  validator: [],
                  widgets: [
                    {
                      id: 3356,
                      field_id: 778,
                      value: '100001',
                      text: '陈贤喜',
                    },
                    {
                      id: 3357,
                      field_id: 778,
                      value: '110001',
                      text: '罗刚',
                    },
                    {
                      id: 3358,
                      field_id: 778,
                      value: '110002',
                      text: '代涛',
                    },
                    {
                      id: 3359,
                      field_id: 778,
                      value: '110003',
                      text: '谢欢',
                    },
                    {
                      id: 3360,
                      field_id: 778,
                      value: '110004',
                      text: '岳海生',
                    },
                    {
                      id: 3361,
                      field_id: 778,
                      value: '110005',
                      text: '肖龙伟',
                    },
                    {
                      id: 3362,
                      field_id: 778,
                      value: '110006',
                      text: '胡长蜜',
                    },
                    {
                      id: 3363,
                      field_id: 778,
                      value: '110007',
                      text: '夏克华',
                    },
                    {
                      id: 3364,
                      field_id: 778,
                      value: '110009',
                      text: '贾桃',
                    },
                    {
                      id: 3365,
                      field_id: 778,
                      value: '110013',
                      text: '郭中华',
                    },
                    {
                      id: 3366,
                      field_id: 778,
                      value: '110014',
                      text: '周德微',
                    },
                    {
                      id: 3367,
                      field_id: 778,
                      value: '110015',
                      text: '叶长久',
                    },
                    {
                      id: 3368,
                      field_id: 778,
                      value: '110016',
                      text: '柴恭如',
                    },
                    {
                      id: 3369,
                      field_id: 778,
                      value: '110017',
                      text: '杨德高',
                    },
                    {
                      id: 3370,
                      field_id: 778,
                      value: '110019',
                      text: '罗双',
                    },
                    {
                      id: 3371,
                      field_id: 778,
                      value: '110022',
                      text: '窦佳佳',
                    },
                    {
                      id: 3372,
                      field_id: 778,
                      value: '110023',
                      text: '徐倚枫',
                    },
                    {
                      id: 3373,
                      field_id: 778,
                      value: '110024',
                      text: '陈国平',
                    },
                    {
                      id: 3374,
                      field_id: 778,
                      value: '110028',
                      text: '冯成刚',
                    },
                    {
                      id: 3375,
                      field_id: 778,
                      value: '110033',
                      text: '唐洪秀',
                    },
                  ],
                },
                {
                  id: 779,
                  key: 'shop',
                  name: '店铺单选',
                  description: '',
                  type: 'shop',
                  is_checkbox: 0,
                  condition: null,
                  region_level: null,
                  min: '',
                  max: '',
                  scale: 0,
                  default_value: {
                    value: 'lsw2729',
                    text: '河南C02.南阳市ODVS-400A1+C',
                  },
                  options: [],
                  form_id: 41,
                  form_grid_id: 41,
                  sort: 4,
                  field_api_configuration_id: null,
                  row: 1,
                  col: 4,
                  x: 4,
                  y: 2,
                  mobile_y: null,
                  validator_id: [],
                  available_options: [
                    {
                      value: 'lsc1233',
                      text: '西藏B12.山南市TPN-50B2',
                    },
                    {
                      value: 'lsw2729',
                      text: '河南C02.南阳市ODVS-400A1+C',
                    },
                    {
                      value: 'lsc1203',
                      text: '四川B12.宜宾市14店KEDD-120A1',
                    },
                    {
                      value: 'lsc1374',
                      text: '陕西C02.延安市宜川县JB-47C',
                    },
                    {
                      value: 'lsw2755',
                      text: '江苏C02.苏州盛泽镇4店HLMP-350A2+C',
                    },
                    {
                      value: 'lsc1345',
                      text: '青海C02.海东市民和县LL-100A2',
                    },
                    {
                      value: 'lsw2673',
                      text: '上海C02.川沙镇TLW-120B2',
                    },
                    {
                      value: 'lsc1406',
                      text: '四川C02.成都市青白江5店QPL-150A2',
                    },
                    {
                      value: 'lsw2683',
                      text: '浙江C02.余姚市BL-120B2',
                    },
                    {
                      value: 'lsc1332',
                      text: '云南C01.文山市4店BXN-260A2',
                    },
                  ],
                  validator: [],
                  widgets: [
                    {
                      id: 3376,
                      field_id: 779,
                      value: 'lsc1233',
                      text: '西藏B12.山南市TPN-50B2',
                    },
                    {
                      id: 3377,
                      field_id: 779,
                      value: 'lsw2729',
                      text: '河南C02.南阳市ODVS-400A1+C',
                    },
                    {
                      id: 3378,
                      field_id: 779,
                      value: 'lsc1203',
                      text: '四川B12.宜宾市14店KEDD-120A1',
                    },
                    {
                      id: 3379,
                      field_id: 779,
                      value: 'lsc1374',
                      text: '陕西C02.延安市宜川县JB-47C',
                    },
                    {
                      id: 3380,
                      field_id: 779,
                      value: 'lsw2755',
                      text: '江苏C02.苏州盛泽镇4店HLMP-350A2+C',
                    },
                    {
                      id: 3381,
                      field_id: 779,
                      value: 'lsc1345',
                      text: '青海C02.海东市民和县LL-100A2',
                    },
                    {
                      id: 3382,
                      field_id: 779,
                      value: 'lsw2673',
                      text: '上海C02.川沙镇TLW-120B2',
                    },
                    {
                      id: 3383,
                      field_id: 779,
                      value: 'lsc1406',
                      text: '四川C02.成都市青白江5店QPL-150A2',
                    },
                    {
                      id: 3384,
                      field_id: 779,
                      value: 'lsw2683',
                      text: '浙江C02.余姚市BL-120B2',
                    },
                    {
                      id: 3385,
                      field_id: 779,
                      value: 'lsc1332',
                      text: '云南C01.文山市4店BXN-260A2',
                    },
                  ],
                },
                {
                  id: 780,
                  key: 'shops',
                  name: '店铺多选',
                  description: '',
                  type: 'shop',
                  is_checkbox: 1,
                  condition: null,
                  region_level: null,
                  min: '',
                  max: '',
                  scale: 0,
                  default_value: '',
                  options: [],
                  form_id: 41,
                  form_grid_id: 41,
                  sort: 5,
                  field_api_configuration_id: null,
                  row: 2,
                  col: 8,
                  x: 0,
                  y: 4,
                  mobile_y: null,
                  validator_id: [],
                  available_options: [],
                  validator: [],
                  widgets: [],
                },
                {
                  id: 781,
                  key: 'interface',
                  name: '接口（单选）',
                  description: '',
                  type: 'api',
                  is_checkbox: 0,
                  condition: null,
                  region_level: null,
                  min: '',
                  max: '',
                  scale: 0,
                  default_value: '4',
                  options: [],
                  form_id: 41,
                  form_grid_id: 41,
                  sort: 6,
                  field_api_configuration_id: 1,
                  row: 1,
                  col: 4,
                  x: 8,
                  y: 5,
                  mobile_y: null,
                  validator_id: [],
                  available_options: [],
                  validator: [],
                  widgets: [],
                },
                {
                  id: 782,
                  key: 'interfaces',
                  name: '接口（多选）',
                  description: '',
                  type: 'api',
                  is_checkbox: 1,
                  condition: null,
                  region_level: null,
                  min: '',
                  max: '8',
                  scale: 0,
                  default_value: '',
                  options: [],
                  form_id: 41,
                  form_grid_id: 41,
                  sort: 7,
                  field_api_configuration_id: 1,
                  row: 1,
                  col: 8,
                  x: 1,
                  y: 6,
                  mobile_y: null,
                  validator_id: [],
                  available_options: [],
                  validator: [],
                  widgets: [],
                },
                {
                  id: 783,
                  key: 'files',
                  name: '图片',
                  description: '',
                  type: 'file',
                  is_checkbox: 0,
                  condition: null,
                  region_level: null,
                  min: '',
                  max: '',
                  scale: 0,
                  default_value: '',
                  options: [],
                  form_id: 41,
                  form_grid_id: 41,
                  sort: 8,
                  field_api_configuration_id: null,
                  row: 2,
                  col: 8,
                  x: 0,
                  y: 7,
                  mobile_y: null,
                  validator_id: [3],
                  available_options: [],
                  validator: [
                    {
                      id: 3,
                      name: '图片格式验证',
                      description: '图片扩展名描述',
                      type: 'mimes',
                      params: 'html,png,jpeg',
                      is_locked: 0,
                      created_at: '2018-10-16 09:58:11',
                      updated_at: '2018-12-04 15:15:44',
                      pivot: {
                        field_id: 783,
                        validator_id: 3,
                      },
                    },
                  ],
                  widgets: [],
                },
                {
                  id: 784,
                  key: 'time',
                  name: '时间',
                  description: '',
                  type: 'time',
                  is_checkbox: 0,
                  condition: null,
                  region_level: null,
                  min: '',
                  max: '19:53:59',
                  scale: 0,
                  default_value: '',
                  options: [],
                  form_id: 41,
                  form_grid_id: 41,
                  sort: 9,
                  field_api_configuration_id: null,
                  row: 1,
                  col: 4,
                  x: 8,
                  y: 7,
                  mobile_y: null,
                  validator_id: [],
                  available_options: [],
                  validator: [],
                  widgets: [],
                },
              ],
            },
          ],
        },
        flow: {
          id: 96,
          name: '表单混合测试',
          description: '',
          icon: '',
          flow_type_id: 1,
          form_id: 41,
          sort: 0,
          number: 6,
          is_active: 1,
          start_callback_uri: '',
          accept_start_callback: '0',
          end_callback_uri: '',
          accept_end_callback: '0',
          send_message: '1',
          is_client: 1,
          created_at: '2019-01-05 11:21:29',
          updated_at: '2019-01-05 11:21:29',
          flows_has_staff: [],
          flows_has_roles: [],
          flows_has_departments: [],
          handle_id: [1, 2, 3, 4],
        },
      },
    },
  },

  subscriptions: {},

  effects: {
    *getFlows(_, { call, put, select }) {
      const { availableFlows } = yield select(model => model.start);
      if (availableFlows.length) {
        return;
      }
      const data = yield call(getFlowList);
      if (data && !data.error) {
        yield put({
          type: 'save',
          payload: {
            store: 'availableFlows',
            data,
          },
        });
      }
    },

    *getFlowInfo({ payload }, { call, put }) {
      const { id, cb } = payload;
      const data = yield call(getFlowInfo, id);
      if (data && !data.error) {
        yield put({
          type: 'save',
          payload: {
            id,
            store: 'flow',
            data,
          },
        });
        if (cb) {
          cb(data);
        }
      }
    },
    *fetchFlowSteps(
      {
        payload: { id, cb },
      },
      { call, put }
    ) {
      const data = yield call(getFlowChart, id);
      if (data && !data.error) {
        yield put({
          type: 'save',
          payload: {
            store: 'flowChart',
            data,
          },
        });
        if (cb) {
          cb(data);
        }
      }
    },
    // 预提交
    *preSet({ payload }, { call, put }) {
      const data = yield call(preSet, payload.data);
      if (data && !data.error) {
        yield put({
          type: 'save',
          payload: {
            store: 'preStepData',
            data,
          },
        });

        if (payload.cb) {
          payload.cb(data);
        }
      } else if (data.status === 422) {
        payload.cb(data);
      }
    },
    // 正式提交
    *stepStart({ payload }, { call }) {
      const data = yield call(stepStart, payload.data);
      if (data && !data.error) {
        payload.cb();
      }
    },

    *fetchStartList({ payload }, { call, put }) {
      const { params } = payload;
      const data = yield call(getStartList, params);
      if (data && !data.error) {
        yield put({
          type: 'save',
          payload: {
            data,
            store: `${params.type}Start`,
          },
        });
      }
    },
    *fetchStepInfo(
      {
        payload: { id, cb },
      },
      { call, put }
    ) {
      const data = yield call(startDetail, id);
      if (data && !data.error) {
        yield put({
          type: 'save',
          payload: {
            data,
            store: 'start',
            id,
          },
        });
        if (cb) {
          cb(data);
        }
      }
    },

    *doWithDraw(
      {
        payload: { params, cb },
      },
      { call, put }
    ) {
      const data = yield call(doWithdraw, params);
      if (data && !data.error) {
        notification.success({
          message: '操作成功',
        });
        yield put({
          type: 'updateList',
          payload: {
            id: params.flow_run_id,
            store: 'processingStart',
            noti: false,
            data,
          },
        });
        if (cb) {
          cb();
        }
      }
    },
  },

  reducers: {
    ...defaultReducers,
  },
};
