import getApiDataSource from '../services/interface';
// import * as defaultReducers from './reducers/default';

export default {
  namespace: 'start',
  state: {
    startDetails: {
      6: {
        step: {
          available_fields: [
            'single',
            'multi',
            'arra',
            'file',
            'area',
            'interface',
            'interfaces',
            'date',
            'text',
            'grid',
            'grid.*.interface',
            'grid.*.interfaces',
            'grid.*.files',
          ],
          hidden_fields: ['date', 'grid.*.interfaces'],
          editable_fields: [
            'single',
            'multi',
            // 'arra',
            'file',
            'area',
            'interface',
            'interfaces',
            'text',
            'address',
            'grid',
            'grid.*.interface',
            'grid.*.files',
          ],
          required_fields: ['grid.*.interface', 'grid', 'file', 'area', 'single', 'multi', 'grid'],
        },
        form_data: {
          file: [],
          number: null,
          area: [],
          single: '给',
          multi: ['发', '额'],
          arra: ['2', '5'],
          interface: 7,
          interfaces: [292],
          date: '2018-11-01',
          text: '',
          address: null,
          grid: [
            { time: '9:01:00', files: [], interfaces: [1], interface: '' },
            { time: '', files: [], interfaces: [4], interface: 3 },
          ],
        },
        fields: {
          form: [
            {
              id: 302,
              key: 'file',
              name: '文件',
              description: '',
              type: 'file',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '',
              max: '',
              scale: 0,
              default_value: '',
              width: '350',
              height: '150',
              x: 50,
              y: 10,
              line: 1,
              options: [],
              form_id: 20,
              form_grid_id: null,
              sort: 0,
              field_api_configuration_id: null,
              validator_id: [7],
              available_options: [],
            },

            {
              id: 303,
              key: 'number',
              name: '数字',
              description: '',
              type: 'int',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '-100',
              max: '',
              scale: 0,
              default_value: '0',
              options: [],
              form_id: 20,
              form_grid_id: null,
              sort: 1,
              field_api_configuration_id: null,
            },
            {
              id: 304,
              key: 'area',
              name: '地点',
              description: '',
              type: 'region',
              is_checkbox: 0,
              condition: null,
              region_level: 4,
              min: '',
              max: '',
              scale: 0,
              default_value: [],
              options: [],
              form_id: 20,
              form_grid_id: null,
              sort: 2,
              field_api_configuration_id: null,
            },
            {
              id: 305,
              key: 'single',
              name: '单选',
              description: '',
              type: 'select',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '',
              max: '',
              scale: 0,
              default_value: '给',
              options: ['给', '我', '发'],
              form_id: 20,
              form_grid_id: null,
              sort: 3,
              field_api_configuration_id: null,
            },
            {
              id: 306,
              key: 'multi',
              name: '多选',
              description: '',
              type: 'select',
              is_checkbox: 1,
              condition: null,
              region_level: null,
              min: '2',
              max: '3',
              scale: 0,
              default_value: ['发', '额'],
              options: ['发', '额', '过', 'p', 'h'],
              form_id: 20,
              form_grid_id: null,
              sort: 4,
              field_api_configuration_id: null,
            },
            {
              id: 307,
              key: 'arra',
              name: '数组',
              description: '',
              type: 'array',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '2',
              max: '10',
              scale: 0,
              default_value: ['2', '5'],
              options: [],
              form_id: 20,
              form_grid_id: null,
              sort: 5,
              field_api_configuration_id: null,
            },
            {
              id: 314,
              key: 'interface',
              name: '接口（单选）',
              description: '',
              type: 'api',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '',
              max: '',
              scale: 0,
              default_value: '7',
              options: [],
              form_id: 20,
              form_grid_id: null,
              sort: 12,
              field_api_configuration_id: 1,
            },
            {
              id: 315,
              key: 'interfaces',
              name: '接口（多选）',
              description: '',
              type: 'api',
              is_checkbox: 1,
              condition: null,
              region_level: null,
              min: '',
              max: '',
              scale: 0,
              default_value: ['292'],
              options: [],
              form_id: 20,
              form_grid_id: null,
              sort: 13,
              field_api_configuration_id: 2,
            },
            {
              id: 316,
              key: 'date',
              name: '日期',
              description: '',
              type: 'date',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '',
              max: '',
              scale: 0,
              default_value: '2018-11-01',
              options: [],
              form_id: 20,
              form_grid_id: null,
              sort: 14,
              field_api_configuration_id: null,
            },
            {
              id: 317,
              key: 'text',
              name: '文本',
              description: '',
              type: 'text',
              is_checkbox: 0,
              condition: null,
              region_level: null,
              min: '1',
              max: '9',
              scale: 0,
              default_value: '',
              options: [],
              form_id: 20,
              form_grid_id: null,
              sort: 15,
              field_api_configuration_id: null,
            },
          ],
          grid: [
            {
              id: 15,
              name: '控件1',
              key: 'grid',
              form_id: 20,
              field_default_value: {
                interface: '4',
                interfaces: '',
                files: ['/storage/uploads/temporary/2018/12/08/120752_20181208113704_754080.png'],
                time: '08:55:55',
              },
              fields: [
                {
                  id: 327,
                  key: 'time',
                  name: '时间',
                  description: '',
                  type: 'time',
                  is_checkbox: 0,
                  condition: null,
                  region_level: null,
                  min: '',
                  max: '19:53:59',
                  scale: 0,
                  default_value: '',
                  options: [],
                  form_id: 20,
                  form_grid_id: 15,
                  sort: 9,
                  field_api_configuration_id: null,
                },
                {
                  id: 326,
                  key: 'files',
                  name: '图片',
                  description: '',
                  type: 'file',
                  is_checkbox: 0,
                  condition: null,
                  region_level: null,
                  min: '',
                  max: '',
                  scale: 0,
                  default_value: '',
                  options: [],
                  form_id: 20,
                  form_grid_id: 15,
                  sort: 8,
                  field_api_configuration_id: null,
                },
                {
                  id: 325,
                  key: 'interfaces',
                  name: '接口（多选）',
                  description: '',
                  type: 'api',
                  is_checkbox: 1,
                  condition: null,
                  region_level: null,
                  min: '',
                  max: '8',
                  scale: 0,
                  default_value: '',
                  options: [],
                  form_id: 20,
                  form_grid_id: 15,
                  sort: 7,
                  field_api_configuration_id: 1,
                },
                {
                  id: 324,
                  key: 'interface',
                  name: '接口（单选）',
                  description: '',
                  type: 'api',
                  is_checkbox: 0,
                  condition: null,
                  region_level: null,
                  min: '',
                  max: '',
                  scale: 0,
                  default_value: '4',
                  options: [],
                  form_id: 20,
                  form_grid_id: 15,
                  sort: 6,
                  field_api_configuration_id: 1,
                },
              ],
            },
          ],
        },
      },
    },
  },

  subscriptions: {},

  effects: {
    *fetchApi({ payload }, { call, put, select }) {
      const { id, cb } = payload;
      const { sourceDetails } = yield select(_ => _.interfaceApi);
      if (sourceDetails[id] && sourceDetails[id].length) {
        return;
      }
      const data = yield call(getApiDataSource, id);
      if (data && !data.error) {
        yield put({
          type: 'save',
          payload: {
            store: 'source',
            id,
            data,
          },
        });
        if (cb) {
          cb(data);
        }
      }
    },
  },

  reducers: {
    save(state, action) {
      const { store, id, data } = action.payload;
      if (id === undefined) {
        return {
          ...state,
          [store]: data,
        };
      }
      const originalStore = state[`${store}Details`];
      return {
        ...state,
        [`${store}Details`]: {
          ...originalStore,
          [id]: data,
        },
      };
    },
  },
};
