module.exports = {
  navTheme: 'light',
  primaryColor: '#1890ff',
  disabledColor: '#666',
  disabledBg: '#f0f0f0',
  disabledColorDark: '#666',
  inputColor: '#666',
  errorColor: '#D9333F',
  btnDangerBg: '#fff',
  layout: 'sidemenu',
  contentWidth: 'Fluid',
  fixedHeader: false,
  autoHideHeader: false,
  fixSiderbar: false,
  collapse: true,
};
